Repository YazdanZ/McGill-ECSE428-Project, pull requests merged in 2023-02, with the labels that each got.

#59 Logout Button for drivers and passengers
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/components/button/Logout.jsx
  package-lock.json
  package.json
Labels: Frontend

#63 Sami/initialize backend
  backend/app.py
Labels: Backend

#61 27 display trip to the passenger frontend functionality
  frontend/src/App.js
  frontend/src/components/pages/TripDisplay.jsx
  package-lock.json
  trip-cost.css
  trip-cost.html
  trip-cost.js
Labels: Frontend

#69 Implement backend login
  backend/app.py
  backend/instance/mcpool.db
Labels: Backend

#72 Connect login frontend and backend
  frontend/src/components/pages/Login.jsx
  frontend/src/components/pages/Signup.jsx
Labels: Backend

#71 getAvailableDrivers API done
  .gitignore
  backend/app.py
Labels: Backend

#83 Sami/gherkin login
  backend/__pycache__/app.cpython-39.pyc
  backend/instance/mcpool.db
  features/login.feature
  frontend/src/components/pages/Login.jsx
  frontend/src/components/pages/Signup.jsx
  steps/login.py
Labels: Testing

#85 Trip display testing
  backend/__pycache__/__init__.cpython-39.pyc
  backend/__pycache__/app.cpython-39.pyc
  backend/__pycache__/database_model.cpython-39.pyc
  backend/__pycache__/user.cpython-39.pyc
  backend/app.py
  backend/instance/mcpool.db
  backend/sql_queries/delete.sql
  features/DisplayTripCost.feature
  features/TripDisplay.feature
  frontend/src/components/pages/Login.jsx
  frontend/src/components/pages/TripDisplay.jsx
  steps/TripDisplay_steps.py
Labels: Testing

#84 Himel/tests
  README.md
  backend/app.py
  tests/environment.py
  tests/features/Signup.feature
  tests/steps/steps.py
Labels: Testing

#88 Mihir task2
  .DS_Store
  .idea/McPool.iml
  .idea/misc.xml
  README.md
  backend/.DS_Store
  backend/__pycache__/app.cpython-38.pyc
  backend/app.py
  backend/instance/mcpool.db
  frontend/src/components/pages/Create_Trip.jsx
  tests/features/Create_Trip.feature
  tests/steps/Create_Trip.py
Labels: Testing

#87 Display availlable trips
  backend/__pycache__/testGetAvailableTrips.cpython-38.pyc
  backend/app.py
  backend/testGetAvailableTrips.py
  behave.ini
  frontend/package-lock.json
  frontend/src/App.js
  frontend/src/components/pages/AvailableDrivers.jsx
  geckodriver.log
  instance/mcpool.db
  pretty.output
  tests/features/.DS_Store
  tests/features/AssignPassengerToTrip.feature
  tests/features/GetAvailableTrips.feature
  tests/steps/AssignPassengerToTrip.py
  tests/steps/GetAvailableTrips.py
Labels: Testing
